Name: Check Solutions

on:
  push
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check Solutions
        run: ${{ github.workspace }}/.github/scripts/check-solutions.sh
        shell: bash
        working-directory: ${{ github.workspace }}
